info:
  app:
    uuid: ${instanceId}

spring:
  application:
    name: tiny-url-backend
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health-check
        healthCheckInterval: 20s
        enabled: true
        instanceId: ${spring.application.name}:${info.app.uuid}
    etcd:
      endpoints: "http://localhost:21379,http://localhost:22379,http://localhost:23379"
  cassandra:
    contact-points: localhost:9042,localhost:9043,localhost:9044
    datacenter: datacenter1
    keyspace: dev
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 0
