info:
  app:
    uuid: ${instanceId}

spring:
  application:
    name: srd-greeter
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health-check
        healthCheckInterval: 20s
        enabled: true
        instanceId: ${spring.application.name}:${info.app.uuid}

server:
  port: 0
