spring:
  application:
    name: tiny-url-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
        registerHealthCheck: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tiny-url
          uri: lb://tiny-url-backend
          predicates:
            - Path=/short-url/**, /url/**
          metadata:
            response-timeout: 500
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT,INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,DELETE
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

server:
  port: 8080
